### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dizel3d**
Fixed typemoq.js URL.
Removed unnecessary tsconfig.json instruction.

### CODE REVIEW

**Comment by florinn** [comment]
Thanks. About the `"module": "umd"` config requirement, it must be set that way to be able to use `import * as TypeMoq from "typemoq"` in the test script and then load the script in the browser without getting the error `'require' is undefined`.

**Comment by dizel3d** [comment]
It means that smth is wrong. In which case do you get the error?

**Comment by dizel3d** [comment]
As for me it looks good. https://jsfiddle.net/dizel3d/m113qxbp/
image

**Comment by florinn** [comment]
Afaik the `'require' is undefined` is due to the import form `import * as TypeMoq from "typemoq"` and not to the lodash dependency. 

So for module `None` there's no loading error but a compile error due to the import form.
For `AMD`, `CommonJS`, `System`, `ES2015`, no compile error but a loading error.

Only `UMD` works both at compile and loading. I guess it makes some sense if you think about it.

**Comment by dizel3d** [comment]
Why you do `import` if you use `typemoq` as global? It's incorrect.

**Comment by dizel3d** [comment]
`typemoq` is UMD. It means you has 3 ways to use it:
1. None (global)
```html
<script src="lodash"></script>
<script src="typemoq"></script>
<script>
  TypeMoq.setup(...)...
</script>
```
2. AMD
```html
<script src="requirejs"></script>
<script>
  requirejs(['myTest']);
</script>
```
where module `myTest` is
```ts
import * as TypeMoq from "typemoq"
TypeMoq.setup(...)...
```
2. CommonJS
```ts
import * as TypeMoq from "typemoq"
TypeMoq.setup(...)...
```

**Comment by florinn** [comment]
Yes, the right way to use it in a browser would be without the import form, but I don't think it's possible, at least for the moment.

Solving #25 would require TS to allow commonjs module concatenation and also to bundle up the type definitions. 
Atm none of these is possible:
https://github.com/Microsoft/TypeScript/pull/5090
https://github.com/Microsoft/TypeScript/issues/4433

So I used rollupjs for module concatenation to umd and dts-bundle for type def concat.
The ouput from dts-bundle looks like this: 
```
declare module 'typemoq' {
...
```
which is usable only with the import form `import * as TypeMoq from "typemoq"`

To be able to use typemoq in the browser without the import form, bundle-dts had to be able to output smth like:
```
declare namespace TypeMoq {
... 
```

**Comment by dizel3d** [comment]
`bundle-dts` is not what you need, it solves CommonJS bundling problem. I offer you another trick, that I use today:
1. build the library with `"module": "commonjs"`
2. remove `import` statements from d.ts files, then concatenate them.

**Comment by florinn** [comment]
Thanks for the tip, I'm going to try it when I have some time.
In the meantime, a PR (this one or a new one) would be welcomed.

**Comment by dizel3d** [comment]
Yes, you're right. I think, global module is a rare use-case. Therefore don't waste your time to fix it. :-)

**Comment by florinn** [comment]
It's not broken, just limited to UMD for the global module :)

I've fixed the broken url with this commit 730646cd8600dacf80e8ca8c53d8fd6350b27bf4 Closing this.

**Pull request closed without merging**
